- team/build.gradle
- team/src/main/java/sansam/team/config/MybatisConfig.java
- team/src/main/java/sansam/team/test/query/controllers/TestQueryController.java
- team/src/main/java/sansam/team/test/query/mappers/TestMapper.java
- team/src/main/java/sansam/team/test/query/servicies/TestQueryDTO.java
- team/src/main/java/sansam/team/test/query/servicies/TestQueryService.java
- team/src/main/resources/sansam/team/test/query/mappers/TestMapper.xml
- team/src/test/java/sansam/team/test/query/services/TestQueryServiceTest.java
close #9 
<br>
<br>
- Mybatis 연동 및 테스트 코드 추가
> [FEAT] Mybatis 연동 및 테스트 코드 추가

- team/src/main/java/sansam/team/config/SwaggerConfig.java
close #11 
<br>
<br>
- 
<br>
-
> [FEAT] 테스트 완료

- docker-compose.yml
- team/build.gradle
- team/src/main/java/sansam/team/common/FileUploadDTO.java
- team/src/main/java/sansam/team/common/FileUploadUtil.java
- team/src/main/java/sansam/team/config/S3Config.java
- team/src/main/java/sansam/team/test/command/controllers/TestController.java
- team/src/main/resources/application.yml
close #15 
<br>
<br>
- S3 연동 및 테스트 코드 작성 완료
> [FEAT] S3 연동 및 테스트 코드 작성 완료

- team/build.gradle
- team/src/main/resources/application.yml
- team/src/main/resources/log4jdbc.log4j2.properties
- team/src/main/resources/logback-spring.xml
close #{19}
<br>
<br>
- log4jdbc 설정 파일 추가
- log 날짜별 기록 추가
<br>
-
> [FEAT] log4jdbc 설정 파일 추가

- team/build.gradle
- team/src/main/java/sansam/team/common/FileUploadUtil.java
- team/src/main/java/sansam/team/config/BeanConfig.java
- team/src/main/java/sansam/team/config/MybatisConfig.java
- team/src/main/java/sansam/team/test/command/controller/TestController.java
- team/src/main/java/sansam/team/test/command/dto/TestDTO.java
- team/src/main/java/sansam/team/test/command/entity/Test.java
- team/src/main/java/sansam/team/test/command/repository/TestRepository.java
- team/src/main/java/sansam/team/test/command/service/TestService.java
- team/src/main/java/sansam/team/test/query/controller/TestQueryController.java
- team/src/main/java/sansam/team/test/query/dto/TestQueryDTO.java
- team/src/main/java/sansam/team/test/query/mapper/TestMapper.java
- team/src/main/java/sansam/team/test/query/service/TestQueryService.java
- team/src/main/resources/application.yml
- team/src/main/resources/log4jdbc.log4j2.properties
- team/src/main/resources/logback-spring.xml
- team/src/main/resources/mapper/test/TestMapper.xml
- team/src/main/resources/sansam/team/test/query/mapper/TestMapper.xml
- team/src/test/java/sansam/team/test/command/service/TestServiceTest.java
- team/src/test/java/sansam/team/test/query/services/TestQueryServiceTest.java
> [REFACTOR] 패키지 변경

- team/src/main/java/sansam/team/common/embedded/Auditable.java
- team/src/main/java/sansam/team/common/embedded/BaseEntity.java
- team/src/main/java/sansam/team/common/jwt/JWTUtil.java
- team/src/main/java/sansam/team/common/s3/FileUploadDTO.java
- team/src/main/java/sansam/team/common/s3/FileUploadUtil.java
- team/src/main/java/sansam/team/config/SecurityConfig.java
- team/src/main/java/sansam/team/filter/JWTFilter.java
- team/src/main/java/sansam/team/filter/LoginFilter.java
- team/src/main/java/sansam/team/project/command/controller/ProjectBoardController.java
- team/src/main/java/sansam/team/project/command/dto/ProjectBoardDTO.java
- team/src/main/java/sansam/team/project/command/entity/ProjectBoard.java
- team/src/main/java/sansam/team/project/command/enums/BoardStatus.java
- team/src/main/java/sansam/team/project/command/repository/ProjectBoardRepository.java
- team/src/main/java/sansam/team/project/command/service/ProjectBoardService.java
- team/src/main/java/sansam/team/test/command/controller/TestController.java
- team/src/main/java/sansam/team/user/command/entity/User.java
- team/src/main/java/sansam/team/user/command/enums/RoleType.java
- team/src/main/java/sansam/team/user/command/service/UserService.java
close #22 
<br>
<br>
- 프로젝트 게시물 CUD 작업 
<br>
- Spring security 권한 문제 및 JWT 토큰 파싱 문제가 생겨서 해당 오류 고침
- 이슈 외 작업 사항 추가로 인해 CRUD 작업 중 CUD까지만 하고 PR 날림
> [FEAT] 프로젝트 게시물 CUD 작업 

- team/src/main/java/sansam/team/common/embedded/Auditable.java
- team/src/main/java/sansam/team/common/embedded/AuditableEntity.java
- team/src/main/java/sansam/team/common/embedded/BaseEntity.java
- team/src/main/java/sansam/team/project/command/controller/ProjectBoardController.java
- team/src/main/java/sansam/team/project/command/entity/ProjectBoard.java
- team/src/main/java/sansam/team/project/command/service/ProjectBoardService.java
- team/src/main/java/sansam/team/project/query/controller/ProjectBoardQueryController.java
- team/src/main/java/sansam/team/project/query/dto/ProjectBoardQueryDTO.java
- team/src/main/java/sansam/team/project/query/mapper/ProjectBoardMapper.java
- team/src/main/java/sansam/team/project/query/service/ProjectBoardQueryService.java
- team/src/main/resources/mapper/project/ProjectBoardMapper.xml
close #24 
<br>
<br>
- 프로젝트 게시물 READ 작업
<br>
- 임베드 날짜 적용 안되는 이슈 해결
- 프로젝트 게시물 CRUD 컨트롤러 Swagger 통합
- 프로젝트 게시물 수정 시 response body 순환 참조 이슈 해결
> [FEAT] 프로젝트 게시물 READ 작업

- team/src/main/java/sansam/team/project/command/controller/ProjectApplyMemberController.java
- team/src/main/java/sansam/team/project/command/controller/ProjectBoardController.java
- team/src/main/java/sansam/team/project/command/dto/projectboard/ProjectApplyMemberDTO.java
- team/src/main/java/sansam/team/project/command/dto/projectboard/ProjectBoardDTO.java
- team/src/main/java/sansam/team/project/command/entity/ProjectApplyMember.java
- team/src/main/java/sansam/team/project/command/entity/ProjectBoard.java
- team/src/main/java/sansam/team/project/command/enums/ApplyStatus.java
- team/src/main/java/sansam/team/project/command/repository/ProjectApplyMemberRepository.java
- team/src/main/java/sansam/team/project/command/service/ProjectApplyMemberService.java
- team/src/main/java/sansam/team/project/command/service/ProjectBoardService.java
- team/src/main/java/sansam/team/user/command/entity/User.java
- team/src/test/java/sansam/team/project/command/service/ProjectApplyMemberServiceTest.java
- team/src/test/java/sansam/team/project/command/service/ProjectBoardServiceTest.java
close #28 
<br>
<br>
- 프로젝트 신청 회원 CUD 작업 및 테스트 코드 작성
> [FEAT] 프로젝트 신청 회원 CUD 작업 및 테스트 코드 작성

- team/src/main/java/sansam/team/project/command/controller/ProjectApplyMemberController.java
- team/src/main/java/sansam/team/project/command/controller/ProjectBoardController.java
- team/src/main/java/sansam/team/project/query/controller/ProjectApplyMemberQueryController.java
- team/src/main/java/sansam/team/project/query/controller/ProjectBoardQueryController.java
- team/src/main/java/sansam/team/project/query/dto/projectboard/ApplyMemberQueryDTO.java
- team/src/main/java/sansam/team/project/query/dto/projectboard/ProjectApplyMemberQueryDTO.java
- team/src/main/java/sansam/team/project/query/dto/projectboard/ProjectBoardQueryDTO.java
- team/src/main/java/sansam/team/project/query/mapper/ProjectApplyMemberMapper.java
- team/src/main/java/sansam/team/project/query/mapper/ProjectBoardMapper.java
- team/src/main/java/sansam/team/project/query/service/ProjectApplyMemberQueryService.java
- team/src/main/java/sansam/team/project/query/service/ProjectBoardQueryService.java
- team/src/main/resources/mapper/project/ProjectApplyMemberMapper.xml
- team/src/main/resources/mapper/project/ProjectBoardMapper.xml
- team/src/test/java/sansam/team/project/query/service/ProjectApplyMemberServiceTest.java
- team/src/test/java/sansam/team/project/query/service/ProjectBoardQueryServiceTest.java
close #30 
<br>
<br>
- 프로젝트 신청 회원 READ 작업 및 테스트 코드 작성
<br>
- Swagger @Operation 속성을 활용한 API 분류 작업
> [FEAT] 프로젝트 신청 회원 READ 작업 및 테스트 코드 작성

- team/src/main/java/sansam/team/project/command/entity/Project.java
- team/src/main/java/sansam/team/project/command/enums/ProjectStatus.java
close #32 
<br>
<br>
- 프로젝트 엔티티 생성
> [FEAT] 프로젝트 엔티티 생성

- team/src/main/resources/schema.sql
close #36 
<br>
<br>
- DDL 구문 작성 완료
<br>
-
> [FEAT] DDL 구문 완성

- team/src/main/java/sansam/team/common/Yn.java
- team/src/main/java/sansam/team/team/command/entity/TeamChat.java
close #47
<br>
<br>
- 
Y/N 여부 Enum 클래스 생성 및 Type 수정
<br>
-
> Y/N 여부 Enum 클래스 생성

- team/src/main/resources/schema.sql
close #48 
<br>
<br>
- 
<br>
-
> DDL auti_increment 추가 및 fk 수정

- team/src/main/java/sansam/team/common/YesNo.java
- team/src/main/java/sansam/team/common/Yn.java
- team/src/main/java/sansam/team/project/command/entity/Project.java
- team/src/main/java/sansam/team/project/command/entity/ProjectMember.java
- team/src/main/java/sansam/team/team/command/entity/TeamChat.java
close #38
<br>
<br>
- 프로젝트 엔티티 수정 작업
<br>
> [REFACTOR] 프로젝트 엔티티 수정 작업

- team/src/main/java/sansam/team/team/command/entity/Interest.java
- team/src/main/java/sansam/team/team/command/entity/TeamMember.java
close #51
<br>
<br>
- 
Team Member Entity 생성
<br>
-
> Team Member Entity 생성

- team/src/main/java/sansam/team/team/command/entity/TeamMemberScheduleProgress.java
- team/src/main/java/sansam/team/team/command/entity/TeamSchedule.java
close #54
<br>
<br>
- 
팀 일정, 팀원 일정 진행상황 엔티티 추가
<br>
-
> 팀 일정, 팀원 일정 진행상황 엔티티 추가

- team/src/main/java/sansam/team/common/YnType.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/InterestType.java
- team/src/main/resources/schema.sql
> Refactor/enum schema/#65

- team/src/main/java/sansam/team/team/command/application/controller/TeamChatController.java
- team/src/main/java/sansam/team/team/command/application/controller/TeamController.java
- team/src/main/java/sansam/team/team/command/application/dto/TeamChatCreateRequestDTO.java
- team/src/main/java/sansam/team/team/command/application/dto/TeamChatUpdateRequestDTO.java
- team/src/main/java/sansam/team/team/command/application/service/TeamChatService.java
- team/src/main/java/sansam/team/team/command/application/service/TeamService.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/Team.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamChat.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamMember.java
- team/src/main/java/sansam/team/team/command/domain/repository/TeamChatRepository.java
- team/src/main/java/sansam/team/team/command/mapper/TeamChatMapper.java
- team/src/test/java/sansam/team/team/command/application/service/TeamChatServiceTest.java
> [FEAT] 팀 채팅방 생성

- team/src/main/java/sansam/team/project/command/application/service/ProjectBoardService.java
- team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectBoard.java
- team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
- team/src/test/java/sansam/team/project/command/application/service/ProjectBoardServiceTest.java
- team/src/test/java/sansam/team/project/query/service/ProjectBoardQueryServiceTest.java
close #70 
<br>
<br>
- 프로젝트 게시물 READ 테스트 코드 수정
<br>
- 프로젝트 게시물 수정 엔티티 생성자 호출 방식으로 변경
- 프로젝트 게시물 추가 modelMapper 사용 방식으로 테스트 코드 수정
> [REFACTOR] 프로젝트 게시물 READ 테스트 코드 수정

- team/src/main/resources/mapper/user/UserQueryMapper.xml
close #{이슈넘버}
<br>
<br>
- 
<br>
-
> [REFACTOR] user_Seq 추가

- team/src/main/java/sansam/team/config/SecurityConfig.java
- team/src/main/java/sansam/team/user/command/application/controller/UserController.java
- team/src/main/resources/data.sql
더미데이터 권한 MANAGER로 변경 및 페이지 권한 전체 허용 변경
close #{이슈넘버}
<br>
<br>
- 
<br>
-
> [REFACTOR] 권한 설정 변경

- team/src/main/resources/data.sql
close #84 
<br>
<br>
- Insert 구문 추가
> [FEAT] Insert 구문 추가

- team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
- team/src/main/java/sansam/team/project/query/controller/ProjectAdminQueryController.java
- team/src/main/java/sansam/team/project/query/controller/ProjectBoardAdminQueryController.java
- team/src/main/java/sansam/team/project/query/controller/ProjectBoardUserQueryController.java
- team/src/main/java/sansam/team/project/query/controller/ProjectUserQueryController.java
- team/src/main/java/sansam/team/project/query/dto/project/ProjectAdminQueryDTO.java
- team/src/main/java/sansam/team/project/query/dto/project/ProjectAllQueryDTO.java
- team/src/main/java/sansam/team/project/query/dto/project/ProjectUserQueryDTO.java
- team/src/main/java/sansam/team/project/query/mapper/ProjectMapper.java
- team/src/main/java/sansam/team/project/query/service/ProjectQueryService.java
- team/src/main/resources/mapper/project/ProjectMapper.xml
- team/src/main/resources/schema.sql
close #80 
<br>
<br>
- 프로젝트 READ 기능 구현
<br>
> [FEAT] 프로젝트 READ 기능 구현

- team/src/main/java/sansam/team/project/command/application/controller/board/ProjectApplyMemberController.java
- team/src/main/java/sansam/team/project/command/application/controller/board/ProjectBoardController.java
- team/src/main/java/sansam/team/project/command/application/controller/project/ProjectController.java
- team/src/main/java/sansam/team/project/command/application/controller/project/ProjectMemberController.java
- team/src/main/java/sansam/team/project/command/application/service/board/ProjectApplyMemberService.java
- team/src/main/java/sansam/team/project/command/application/service/board/ProjectBoardService.java
- team/src/main/java/sansam/team/project/command/application/service/project/ProjectMemberService.java
- team/src/main/java/sansam/team/project/command/application/service/project/ProjectService.java
- team/src/main/java/sansam/team/project/command/domain/repository/board/ProjectApplyMemberRepository.java
- team/src/main/java/sansam/team/project/command/domain/repository/board/ProjectBoardRepository.java
- team/src/main/java/sansam/team/project/command/domain/repository/project/ProjectMemberRepository.java
- team/src/main/java/sansam/team/project/command/domain/repository/project/ProjectRepository.java
- team/src/main/java/sansam/team/project/command/infrastructure/repository/board/JpaProjectApplyMemberRepository.java
- team/src/main/java/sansam/team/project/command/infrastructure/repository/board/JpaProjectBoardRepository.java
- team/src/main/java/sansam/team/project/command/infrastructure/repository/project/JpaProjectMemberRepository.java
- team/src/main/java/sansam/team/project/command/infrastructure/repository/project/JpaProjectRepository.java
- team/src/main/java/sansam/team/project/query/controller/board/ProjectApplyMemberQueryController.java
- team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardAdminQueryController.java
- team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardUserQueryController.java
- team/src/main/java/sansam/team/project/query/controller/project/ProjectAdminQueryController.java
- team/src/main/java/sansam/team/project/query/controller/project/ProjectUserQueryController.java
기능 별로 디렉토리 구분
close #90 
<br>
<br>
- 프로젝트 도메인 디렉토리 구조 변경
<br>
> [REFACTOR] 프로젝트 도메인 디렉토리 구조 변경

- team/src/main/java/sansam/team/project/command/domain/aggregate/InterestType.java
- team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamMember.java
- team/src/main/resources/data.sql
- team/src/main/resources/schema.sql
팀원 관심분야, 전공 -> 프로젝트 관심분야, 전공으로 수정
table ddl, dml 구문 수정
close #98 
<br>
<br>
- 
<br>
-
> [REFACTOR] 팀원 컬럼 및 프로젝트 회원 컬럼 수정

- docker-compose.yml
close #99 
<br>
<br>
- MongoDB docker 연동
> [FEAT MongoDB 연동 완료

- team/src/main/java/sansam/team/project/command/application/dto/project/ProjectMemberUpdateDTO.java
- team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
- team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
- team/src/main/resources/data.sql
- team/src/main/resources/schema.sql
projectApplyMember, projectMember 수정
commitScore 추가
close #102 
<br>
<br>
- 
<br>
-
> [REFACTOR] projectMember 수정

- team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
- team/src/main/resources/data.sql
- team/src/main/resources/schema.sql
프로젝트 멤버 컬럼 수정
close #106 
<br>
<br>
- 
<br>
-
> [REFACTOR] 프로젝트 멤버 컬럼 수정

- team/src/main/java/sansam/team/team/command/application/dto/TeamReviewDTO.java
- team/src/main/java/sansam/team/team/command/application/service/TeamReviewService.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/TeamStatusType.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/Team.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamReview.java
- team/src/main/java/sansam/team/team/command/domain/repository/TeamReviewRepository.java
- team/src/main/resources/data.sql
- team/src/main/resources/schema.sql
close #111
<br>
<br>
- 
<br>
-
> [FEAT] TEAM TABLE status, endDate 추가

- team/src/main/java/sansam/team/common/util/DateTimeUtil.java
- team/src/main/java/sansam/team/project/command/application/service/project/ProjectService.java
- team/src/main/java/sansam/team/team/command/application/controller/TeamReviewController.java
- team/src/main/java/sansam/team/team/command/application/service/TeamReviewService.java
close #114
<br>
<br>
- 
<br>
-
> [FEAT] #114_ DateTimeUtil 생성

- team/src/main/java/sansam/team/common/response/ApiResponse.java
- team/src/main/java/sansam/team/exception/ErrorCodeType.java
- team/src/main/java/sansam/team/team/command/application/controller/TeamReviewController.java
- team/src/main/java/sansam/team/team/command/application/service/TeamMemberService.java
- team/src/main/java/sansam/team/team/command/application/service/TeamReviewService.java
- team/src/main/java/sansam/team/team/command/application/service/TeamService.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/Team.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamReview.java
- team/src/main/java/sansam/team/team/command/domain/repository/TeamMemberRepository.java
- team/src/main/java/sansam/team/team/command/domain/repository/TeamRepository.java
- team/src/main/java/sansam/team/team/command/domain/repository/TeamReviewRepository.java
- team/src/main/resources/data.sql
close #{이슈넘버}
<br>
<br>
- 
<br>
-
> [FEAT] 팀원 평가 CRUD 기능 추가

- team/src/main/java/sansam/team/project/command/application/controller/project/ProjectMemberController.java
- team/src/main/java/sansam/team/project/query/controller/board/ProjectApplyMemberQueryController.java
- team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardAdminQueryController.java
- team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardUserQueryController.java
- team/src/main/java/sansam/team/project/query/controller/project/ProjectAdminQueryController.java
- team/src/main/java/sansam/team/project/query/controller/project/ProjectMemberAdminQueryCotroller.java
- team/src/main/java/sansam/team/project/query/controller/project/ProjectMemberUserQueryController.java
- team/src/main/java/sansam/team/project/query/service/ProjectMemberQueryService.java
close #124 
<br>
<br>
- 프로젝트 컨트롤러 반환값 수정
- responseEntity에서 DTO로 봔환하도록 변경
> [REFACTOR] 프로젝트 READ 컨트롤러 반환값 수정

- team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardAdminQueryController.java
- team/src/main/java/sansam/team/project/query/controller/project/ProjectMemberAdminQueryCotroller.java
- team/src/main/java/sansam/team/project/query/dto/project/ProjectMemberAdminAllQueryDTO.java
- team/src/main/java/sansam/team/project/query/mapper/ProjectMemberMapper.java
- team/src/main/java/sansam/team/project/query/service/ProjectMemberQueryService.java
- team/src/main/resources/mapper/project/ProjectMember.xml
close #88 
<br>
<br>
- 프로젝트 멤버 READ 기능 구현 완료
> [FEAT] 프로젝트 멤버 READ 기능 구현 완료

- team/src/main/java/sansam/team/exception/ErrorCodeType.java
- team/src/main/java/sansam/team/exception/GlobalExceptionHandler.java
- team/src/main/java/sansam/team/team/command/application/controller/TeamController.java
- team/src/main/java/sansam/team/team/command/application/dto/TeamScheduleDTO.java
- team/src/main/java/sansam/team/team/command/application/service/TeamService.java
- team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamSchedule.java
- team/src/main/java/sansam/team/team/command/domain/repository/TeamScheduleRepository.java
- team/src/main/java/sansam/team/team/command/infrastructure/repository/JpaTeamScheduleRepository.java
close #120 
<br>
<br>
- 
<br>
-
> [FEAT] 팀 일정 기능 추가
